(() => { "use strict";
const control = "/data/adb/modules/tricky_store/rka-control.sh";
const actions = Object.freeze({ status:"status", "role-donor":"role-donor", "role-candidate":"role-candidate", "pair-direct":"pair-direct", "rotate-pairing":"rotate-pairing", start:"start", stop:"stop", "recover-keystore2":"recover-keystore2", "export-audit":"export-audit", cleanup:"cleanup", quarantine:"quarantine" });
const displayedFields = Object.freeze(["role","phone_role","profile_epoch","direct_profile","direct_readiness","pairing","diagnostic","sentinel","quarantine_count"]); let nonce = ""; const status = document.querySelector("#rka-status"); const commandState = document.querySelector("#command-state");
function parseFields(stdout) { const fields = new Map(); for (const line of String(stdout).split("\n")) { const separator = line.indexOf("="); if (separator > 0) fields.set(line.slice(0, separator), line.slice(separator + 1)); } return fields; }
function setState(message) { commandState.textContent = message; }
function renderStatus(fields) { status.replaceChildren(); for (const name of displayedFields) { const item = document.createElement("div"); const label = document.createElement("dt"); const value = document.createElement("dd"); label.textContent = name.replaceAll("_", " "); value.textContent = fields.get(name) ?? "UNAVAILABLE"; item.append(label, value); status.append(item); } }
function exec(command) { const bridge = globalThis.ksu; if (!bridge || typeof bridge.exec !== "function") return Promise.reject(new Error("KernelSU WebUI bridge unavailable")); return Promise.resolve(bridge.exec(command)); }
async function openSession() { const opened = await exec(`${control} webui-open`); if (opened.errno !== 0) throw new Error("WebUI session was rejected"); nonce = parseFields(opened.stdout).get("nonce") ?? ""; if (!/^[0-9a-f]{32}$/.test(nonce)) throw new Error("WebUI session response was invalid"); }
async function invoke(action) { if (!Object.hasOwn(actions, action) || nonce === "") throw new Error("WebUI request was rejected"); const result = await exec(`${control} webui ${actions[action]} ${nonce}`); if (result.errno !== 0) throw new Error("Fixed control request failed"); const fields = parseFields(result.stdout); const nextNonce = fields.get("next_nonce"); if (nextNonce !== undefined) { if (!/^[0-9a-f]{32}$/.test(nextNonce)) throw new Error("WebUI session rotation was invalid"); nonce = nextNonce; } renderStatus(fields); setState(action === "status" ? "Status refreshed" : "Request accepted"); }
async function handleAction(button) { const action = button.dataset.action; if (action === "cleanup" && !globalThis.confirm("Clear ephemeral RKA runtime state?")) return; button.disabled = true; try { await invoke(action); } catch (error) { setState(error instanceof Error ? error.message : "WebUI request failed"); } finally { button.disabled = false; } }
for (const button of document.querySelectorAll("button[data-action]")) button.addEventListener("click", () => { void handleAction(button); });
void openSession().then(() => invoke("status")).catch((error) => { setState(error instanceof Error ? error.message : "WebUI unavailable"); }); })();
